[workspace]
resolver = "2"
members = [
  "crates/core",
  "crates/db",
  "crates/storage",
  "crates/mailer",
  "crates/auth",
  "crates/domain",
  "crates/realtime",
  "crates/api",
  "crates/server",
  "crates/test-support",
]

[workspace.package]
edition = "2021"
publish = false

[profile.dev.package.argon2]
opt-level = 3

[profile.test]
debug = 1
incremental = false
