-- 0001_init.sql — M0 schema (FROZEN)
-- IDs are UUIDv7, generated by the application (Rust `uuid` crate v7), NOT by Postgres.
-- Enum-like fields use TEXT + CHECK for easy evolution during alpha.
-- Forward-only migration: never edit after it is applied; add a new numbered file.

BEGIN;

CREATE TABLE account (
    id            UUID PRIMARY KEY,
    username      TEXT NOT NULL UNIQUE,
    email         TEXT NOT NULL UNIQUE,
    display_name  TEXT NOT NULL,
    avatar_url    TEXT,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE auth_identity (
    id                   UUID PRIMARY KEY,
    account_id           UUID NOT NULL REFERENCES account(id) ON DELETE CASCADE,
    provider             TEXT NOT NULL CHECK (provider IN ('password','google','github','facebook')),
    provider_account_id  TEXT,
    password_hash        TEXT,                         -- argon2; NULL for OAuth identities
    created_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (provider, provider_account_id)
);
CREATE INDEX idx_auth_identity_account ON auth_identity (account_id);

CREATE TABLE session (
    id                   UUID PRIMARY KEY,
    account_id           UUID NOT NULL REFERENCES account(id) ON DELETE CASCADE,
    token_hash           TEXT NOT NULL UNIQUE,         -- sha256 hex of the opaque token
    created_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_used_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    absolute_expires_at  TIMESTAMPTZ NOT NULL,
    revoked_at           TIMESTAMPTZ
);
CREATE INDEX idx_session_account ON session (account_id);

CREATE TABLE server (
    id                UUID PRIMARY KEY,
    owner_account_id  UUID NOT NULL REFERENCES account(id) ON DELETE RESTRICT,
    name              TEXT NOT NULL,
    icon_url          TEXT,
    visibility        TEXT NOT NULL DEFAULT 'private'
                          CHECK (visibility IN ('public','private','unlisted')),
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_server_owner ON server (owner_account_id);

CREATE TABLE channel (
    id          UUID PRIMARY KEY,
    server_id   UUID REFERENCES server(id) ON DELETE CASCADE,  -- NULL for dm/group_dm
    kind        TEXT NOT NULL CHECK (kind IN ('text','dm','group_dm')),
    name        TEXT,
    position    INT,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    CHECK (
        (kind = 'text'                 AND server_id IS NOT NULL) OR
        (kind IN ('dm','group_dm')     AND server_id IS NULL)
    )
);
CREATE INDEX idx_channel_server ON channel (server_id);

CREATE TABLE membership (
    id          UUID PRIMARY KEY,
    server_id   UUID NOT NULL REFERENCES server(id) ON DELETE CASCADE,
    account_id  UUID NOT NULL REFERENCES account(id) ON DELETE CASCADE,
    nickname    TEXT,                                  -- per-server identity; nullable now
    role        TEXT NOT NULL DEFAULT 'member' CHECK (role IN ('owner','member')),
    joined_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (server_id, account_id)
);
CREATE INDEX idx_membership_account ON membership (account_id);

CREATE TABLE channel_member (
    id          UUID PRIMARY KEY,
    channel_id  UUID NOT NULL REFERENCES channel(id) ON DELETE CASCADE,
    account_id  UUID NOT NULL REFERENCES account(id) ON DELETE CASCADE,
    added_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (channel_id, account_id)
);
CREATE INDEX idx_channel_member_account ON channel_member (account_id);

CREATE TABLE message (
    id                 UUID PRIMARY KEY,               -- UUIDv7 => chronological
    channel_id         UUID NOT NULL REFERENCES channel(id) ON DELETE CASCADE,
    author_account_id  UUID NOT NULL REFERENCES account(id) ON DELETE RESTRICT,
    content            TEXT NOT NULL,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    edited_at          TIMESTAMPTZ,
    deleted_at         TIMESTAMPTZ
);
-- newest-first pagination within a channel
CREATE INDEX idx_message_channel ON message (channel_id, id DESC);

CREATE TABLE friendship (
    id            UUID PRIMARY KEY,
    account_low   UUID NOT NULL REFERENCES account(id) ON DELETE CASCADE,
    account_high  UUID NOT NULL REFERENCES account(id) ON DELETE CASCADE,
    status        TEXT NOT NULL CHECK (status IN ('pending','accepted')),
    requested_by  UUID NOT NULL REFERENCES account(id),
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    CHECK (account_low < account_high),                -- canonical single row
    UNIQUE (account_low, account_high)
);
CREATE INDEX idx_friendship_high ON friendship (account_high);

CREATE TABLE block (
    id                  UUID PRIMARY KEY,
    blocker_account_id  UUID NOT NULL REFERENCES account(id) ON DELETE CASCADE,
    blocked_account_id  UUID NOT NULL REFERENCES account(id) ON DELETE CASCADE,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (blocker_account_id, blocked_account_id)
);
CREATE INDEX idx_block_blocked ON block (blocked_account_id);

COMMIT;
