-- 0017_account_profiles_m1.sql — persisted profile settings and ordered links.
--
-- No BEGIN/COMMIT: sqlx wraps each migration in its own transaction.
-- IDs remain UUIDv7 values generated by Rust; account_profile_link.id has no
-- database default.

CREATE TYPE presence_status AS ENUM ('online', 'idle', 'dnd', 'invisible');
CREATE TYPE visibility AS ENUM ('public', 'friends', 'private');

ALTER TABLE account
    ADD COLUMN status             presence_status NOT NULL DEFAULT 'online',
    ADD COLUMN custom_status      TEXT,
    ADD COLUMN custom_emoji       TEXT,
    ADD COLUMN custom_expires_at  TIMESTAMPTZ,
    ADD COLUMN theme              JSONB NOT NULL DEFAULT '{}'::jsonb,
    ADD COLUMN vis_bio            visibility NOT NULL DEFAULT 'public',
    ADD COLUMN vis_communities    visibility NOT NULL DEFAULT 'friends',
    ADD COLUMN vis_friends        visibility NOT NULL DEFAULT 'friends',
    ADD COLUMN deleted_at         TIMESTAMPTZ;

ALTER TABLE account
    ADD CONSTRAINT account_custom_status_len CHECK (
        custom_status IS NULL OR char_length(custom_status) <= 128
    );

CREATE TABLE account_profile_link (
    id         UUID PRIMARY KEY,
    account_id UUID NOT NULL REFERENCES account(id) ON DELETE CASCADE,
    label      TEXT NOT NULL,
    url        TEXT NOT NULL,
    position   SMALLINT NOT NULL,

    CONSTRAINT label_len CHECK (char_length(label) BETWEEN 1 AND 32),
    CONSTRAINT url_len CHECK (char_length(url) <= 256),
    UNIQUE (account_id, position)
);

CREATE INDEX idx_account_profile_link_account ON account_profile_link(account_id);
